// Electron main process (CommonJS -- Electron's main is rock-solid as CJS;
// ESM main on Electron 31 / Node 20 crashes importing the built-in electron
// module). The COMPOSITION ROOT: it owns the window lifecycle and constructs
// every service, but the wiring seams themselves (env -> services, services ->
// IPC surface, push channels, window options, shutdown) live in
// main/appWiring.js so they unit-test with fakes (audit D2). This file remains
// the ONLY sanctioned wiring point for the W3 head-tracking receiver.
//
// Config precedence everywhere: an env var that is SET wins over persisted
// settings (shared/settings.js `resolveEffective`); with no env vars and a
// fresh settings file the app behaves exactly like the pre-settings build.

const { app, BrowserWindow, dialog, ipcMain } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const { MediamtxSupervisor } = require('./mediamtx.js');
const { IphoneTelemetryBridge } = require('./IphoneTelemetryBridge.js');
const { HeadTrackingReceiver } = require('./HeadTrackingReceiver.js');
const { w3ConfigFor } = require('./headTrackingConfig.js');
const { createSettingsStore } = require('./settingsStore.js');
const { SessionRuntime } = require('./sessionRuntime.js');
const { createQuitPolicy } = require('./quitPolicy.js');
const { ElrsLauncher } = require('./elrsLauncher.js');
const { HostProbe } = require('./hostProbe.js');
const { createRemoteAddrHint } = require('./remoteAddrHint.js');
const feel = require('../shared/feelConstants.js');
const {
  PUSH_CHANNELS,
  createNetworkServices,
  telemetrySourceFor,
  createSessionApplier,
  createKeyedInstance,
  mediamtxPaths,
  registerIpcHandlers,
  wireHotspotPush,
  createWindowOptions,
  installNavigationPolicy,
  createTeardown,
} = require('./appWiring.js');

const projectRoot = path.join(__dirname, '..');
const log = (m) => console.log(m);

// WHEP endpoint the renderer connects to (mediamtx default WebRTC port 8889).
const WHEP_URL = process.env.W17_WHEP_URL || 'http://127.0.0.1:8889/cam/whep';

// Session-scoped state, owned by whenReady below.
let mediamtx = null;
let settingsStore = null;
let runtime = null;
let sessionApplier = null;

// Setup-flow platform services (thin IO; all soft-fail with reasons). The
// hotspot lifecycle constructed here is THE runtime authority (audit B1): the
// same instance answers the IPC queries, feeds the renderer push, and gates
// the quit policy.
const { wifi, hotspotLifecycle, sim } = createNetworkServices({ env: process.env, log });
wireHotspotPush({
  lifecycle: hotspotLifecycle,
  broadcast: (channel, snap) => {
    for (const win of BrowserWindow.getAllWindows()) {
      if (!win.isDestroyed()) win.webContents.send(channel, snap);
    }
  },
});
const elrs = new ElrsLauncher({ log });
const hostProbe = new HostProbe();
// Last accepted W3 datagram's SENDER IP (transport metadata only) — feeds the
// setup screen's address suggestion; the user always confirms it by hand.
const addrHint = createRemoteAddrHint();

// iPhone -> Windows head-tracking receiver (contract section 3): LOG-ONLY.
// It is a dead end by construction -- nothing consumes its data; it logs and
// counts. It must never feed CRSF, servos, pan/tilt, telemetry, or the
// renderer (separate safety milestone required). Its wiring lives ONLY here:
// the keyed holder carries just the restart choreography (idempotent
// re-apply, stop-before-replace, stop-on-null — tested with fakes), while the
// receiver itself is constructed in THIS file and nowhere else.
const w3Receiver = createKeyedInstance({
  construct: (cfg) => new HeadTrackingReceiver({
    ...cfg,
    log,
    noteRemoteAddr: addrHint.note,
  }),
});

function applyW3(effective) {
  return w3Receiver.apply(w3ConfigFor(effective, process.env));
}

function createWindow() {
  // Taskbar/window icon (Windows/Linux; macOS uses the bundle's .icns). The
  // PNG is generated by `npm run icon` and committed under build/.
  const iconPath = path.join(projectRoot, 'build', 'icon.png');
  const win = new BrowserWindow(createWindowOptions({
    preloadPath: path.join(__dirname, 'preload.cjs'),
    iconPath: fs.existsSync(iconPath) ? iconPath : null,
  }));
  installNavigationPolicy(win.webContents, { log });

  runtime.setSnapshotSink((t) => {
    if (!win.isDestroyed()) win.webContents.send(PUSH_CHANNELS.telemetry, t);
  });

  win.loadFile(path.join(projectRoot, 'renderer', 'index.html'));
  return win;
}

app.whenReady().then(async () => {
  const { binaryPath, configPath } = mediamtxPaths({
    env: process.env,
    platform: process.platform,
    isPackaged: app.isPackaged,
    resourcesPath: process.resourcesPath,
    projectRoot,
  });
  mediamtx = new MediamtxSupervisor({ binaryPath, configPath, log });
  mediamtx.start();

  settingsStore = createSettingsStore({
    dir: app.getPath('userData'),
    log,
  });

  // linkState lives in an ES module (shared/linkState.mjs, consumed by the
  // renderer + vitest); load it dynamically so the bridge derives link state
  // with the exact same logic as the HUD. Only used when the bridge is enabled.
  const { linkState } = await import(pathToFileURL(path.join(projectRoot, 'shared', 'linkState.mjs')).href);

  runtime = new SessionRuntime({
    createTelemetrySource: (cfg) => telemetrySourceFor(cfg, { platform: process.platform, log }),
    // Windows -> iPhone telemetry bridge (docs/windows_bridge_contract.md — the
    // iPhone app's canonical contract; UDP JSON to port 5601 by default).
    createIphoneBridge: (cfg, { demo }) => new IphoneTelemetryBridge({
      ...cfg,
      linkStateFn: linkState,
      mode: demo ? 'demo' : undefined,
      log,
    }),
    log,
  });

  // Recomputes effective config from persisted settings + env and (re)applies
  // the session runtime; applyW3 keeps the W3 receiver wiring in THIS file.
  sessionApplier = createSessionApplier({
    settingsStore, runtime, env: process.env, applyW3, warn: log,
  });

  registerIpcHandlers({
    ipcMain,
    services: {
      whepUrl: WHEP_URL,
      platform: process.platform,
      feel: {
        gears: feel.GEARS,
        topSpeedKmh: feel.TOP_SPEED_KMH,
        ersDeployPctPerSec: feel.ERS_DEPLOY_PCT_PER_SEC,
        ersHarvestPctPerSec: feel.ERS_HARVEST_PCT_PER_SEC,
        ersBoostMultiplier: feel.ERS_BOOST_MULTIPLIER,
      },
      runtime,
      settingsStore,
      sessionApplier,
      w3Active: () => w3Receiver.active(),
      wifi,
      sim,
      hotspotLifecycle,
      addrHint,
      hostProbe,
      elrs,
    },
  });
  sessionApplier.apply();
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

// Quit policy (audit B1, decision Q1): quitting while THIS APP owns a running
// hotspot asks STOP HOTSPOT AND QUIT / LEAVE HOTSPOT RUNNING / CANCEL. A
// window closing routes through app.quit() -> before-quit, so the same policy
// covers it; nothing else ever stops the hotspot implicitly, and an external
// or inactive hotspot quits without any dialog.
const quitPolicy = createQuitPolicy({
  lifecycle: hotspotLifecycle,
  showDialog: (opts) => dialog.showMessageBox(opts),
  showError: (title, content) => dialog.showErrorBox(title, content),
  quit: () => app.quit(),
  log,
});
app.on('before-quit', (event) => quitPolicy.onBeforeQuit(event));

// Always tear down the children + sources so nothing is orphaned; each step is
// failure-isolated (a throwing stop cannot skip the rest — audit D2). The
// elrs-joystick-control launcher is deliberately absent: it spawns detached
// and is never killed by this app. The hotspot is also deliberately absent:
// its shutdown is decided by the quit policy above, never implicitly.
const teardown = createTeardown({
  steps: [
    ['head-tracking receiver', () => w3Receiver.apply(null)],
    ['session runtime', () => { if (runtime) runtime.stopAll(); }],
    ['mediamtx', () => { if (mediamtx) mediamtx.stop(); }],
  ],
  log,
});
app.on('will-quit', () => teardown());
